<h3>Bloquer un utilisateur</h3>

<div class="Form">

    <form action="" class="Form-box" method="POST" id="blockUserForm">

        <label for="selectUser" ></label>
        <select name="selectUser" id="selectUser" class="FormArticle-box-input">
            <?php foreach ($users as $user):?>
                <option value="<?=$user['id'];?>"><?=$user['pseudo'];?></option>
            <?php endforeach;?>
        </select>

        <div class="FormCategory-button">
            <input type="submit" class="FormArticle-box-button" value="Bloquer l'utilisateur">
        </div>

    </form>

</div>

<script src="<?=asset('js/blockuser.js');?>"></script>