<h3>Messagerie</h3>
<div class="MyMessages">

    <?php include TEMPLATE_DIR . '/admin/message/adminmessages.phtml';?>

    <?php include TEMPLATE_DIR . '/admin/message/table.phtml';?>

        <tbody>

            <?php if (!empty($messages)):?>

                <?php foreach ($messages as $message):?>

                    <tr>
                        <td><?=$message['pseudoFrom'];?></td>
                        <td><?=$message['pseudoTo'];?></td>
                        <td><?=$message['subject'];?></td>
                        <td>Le <?=(new DateTimeImmutable($message['publication_date']))->format('d/m/Y');?> à <?=(new DateTimeImmutable($message['publication_date']))->format('H:i');?></td>
                        <td><a href="<?=buildUrl('message', ['id' => $message['id_message']]);?>">Lire</a></td>
                        <td><a href="<?=buildUrl('messageTrashToUser', ['id' => $message['id_message']]);?>">Supprimer</a></td>
                    </tr>

                <?php endforeach;?>

            <?php endif;?>
            
        </tbody>
    </table>
</div>