<?php use App\Framework\UserSession;?>


<h3>Message</h3>

<div class="MyMessage">

    <p>Sujet : <?=htmlspecialchars($subjectMessage);?></p>
    <p>De : <?=htmlspecialchars($pseudoFrom);?></p>
    <p>À <?=htmlspecialchars($pseudoTo);?></p>
    <p>Message :</p>
    <p><?=htmlspecialchars($messageContent);?></p>

</div>

<?php if ($pseudoFromId != UserSession::getId()):?>

    <div class="FormMessage">

        <form action="" method="POST" class="FormMessage-box">

            <label for="subject" class="FormMessage-box-label">Sujet :</label>
            <input type="text" name="subject" id="" value="<?=htmlspecialchars($subject);?>">

            <label for="content" class="FormMessage-box-label">Message :</label>
            <textarea class="FormMessage-box-textarea" name="content" ><?=htmlspecialchars($content);?></textarea>
            
            <input type="hidden" name="toUser" value="<?=$pseudoFromId;?>">

            <div class="FormMessage-box-buttonBox">
                <button class="FormMessage-box-button" type="submit" name="validate" >Répondre</button>
            </div>

        </form>
    </div>

<?php endif;?>