<h3>Messagerie</h3>
<div class="MyMessages">

    <?php include TEMPLATE_DIR . '/admin/message/adminmessages.phtml';?>

    <?php include TEMPLATE_DIR . '/admin/message/table.phtml';?>

        <tbody>
            <?php if (!empty($messages)):?>

                <?php foreach ($messages as $message):?>

                    <tr>
                        <td><?=htmlspecialchars($message['pseudoFrom']);?></td>
                        <td><?=htmlspecialchars($message['pseudoTo']);?></td>
                        <td><?=htmlspecialchars($message['subject']);?></td>
                        <td><?=$message['publication_date'];?></td>
                        <td><a href="<?=buildUrl('message', ['id' => $message['id_message']]);?>">Lire</a></td>
                        <td><a href="<?=buildUrl('messageTrashFromUser', ['id' => $message['id_message']]);?>">Supprimer</a></td>
                    </tr>

                <?php endforeach;?>

            <?php endif;?>
            
        </tbody>
    </table>
</div>