<?php use App\Framework\UserSession ;?>

<h3 class="TitlePage">Administration</h3>

<div class="container">

    <?php if(UserSession::author() || UserSession::administrator()):?>

        <h4 class="Title">Articles</h4>

    <div class="List">

    <a class="List-link" href="<?=buildUrl('newarticle');?>">Créer un article</a>

        <a class="List-link" href="<?=buildUrl('myarticles');?>">Gérer mes articles</a>

        <!-- <p><a href="<?=buildUrl('uploadFile');?>">Charger des fichiers</a></p> -->

    </div>


    <?php endif;?>

    <?php if(UserSession::administrator()):?>

        <h4 class="Title">Membres</h4>

    <div class="List">

        <a class="List-link" href="<?=buildUrl('adminusers');?>">Gérer les membres</a>

    </div>

    <h4 class="Title">Commentaires</h4>

    <div class="List">

        <a class="List-link" href="<?=buildUrl('commentsAdministration');?>">Modérer les commentaires</a>

    </div>

        <h4 class="Title">Catégories</h4>

        <div class="List">

            <a class="List-link" href="<?=buildUrl('addCategory');?>">Créer une catégorie</a>

            <a class="List-link" href="<?=buildUrl('adminCategories');?>">Gérer les catégories</a>

        </div>

</div>


<?php endif;?>

<?php if (UserSession::newRegistered()):?>

    <p>Bienvenue nouvel(lle) uutilisateur(trice) ! Veuillez patienter pendant qu'un administrateur vous donne accès à la création de vos articles. </p>

<?php endif;?>