<?php use App\Framework\UserSession;?>

<h3 class="TitlePage">Administrer les articles non approuvés</h3>

<?php if (!empty($notApprouvedArticles)):?>

<table>
    <thead>
        <tr>
            <th>Id</th>
            <th>Titre</th>
            <th>Contenu</th>
            <th>Image</th>
            <th>Pseudo</th>
            <th colspan="2">Actions</th>
        </tr>
    </thead>
    <tbody>
            
        <?php foreach ($notApprouvedArticles as $notApprouvedArticle):?>

            <tr id="article-<?=$notApprouvedArticle['id'];?>">
                <td><?= $notApprouvedArticle['id'];?></td>
                <td><?=htmlspecialchars(substr($notApprouvedArticle['title'], 0, 100));?> [...]</a></td>
                <td><?=$notApprouvedArticle['content'], 0, 100;?> [...]</a></td>
                <?php $image = $notApprouvedArticle['image'] != null ? "<img class='td-img' src=" . asset('img/imgArticle/' . $notApprouvedArticle['image']) . " alt=".$notApprouvedArticle['image']." </img>  " : 'Article sans image';?>
                <td><?=$image;?></td>
                <td><?=$notApprouvedArticle['pseudo'];?></td>
                <td><a id="a-approuve" class="confirmation" href="<?=buildUrl('approuveArticle', ['id' => intval($notApprouvedArticle['id']), 'token' => UserSession::token()]);?>">Approuver</a></td>
                <td><a id="a-delete" class="confirmation"  href="<?=buildUrl('deleteNotApprouvedArticle', ['id' => intval($notApprouvedArticle['id']), 'token' => UserSession::token()]);?>">Supprimer</a></td>
            </tr>

        <?php endforeach;?>
        
    </tbody>
</table>

<?php else:?>

    <p>Il n'y a pas d'articles à modérer pour le moment.</p>

<?php endif;?>

<script src="<?=asset('js/adminnotapprouvedarticles.js');?>" ></script>