<?php use App\Framework\UserSession;?>


<h3 class="TitlePage">Supprimer l'utilisateur <?= htmlspecialchars($userInfos['pseudo']);?></h3>

<div class="Form">

    <form class="Form-box" method="POST" action="">
        <div class="Form-box-div">
            <label class="Form-box-label" for="deleteuser"></label>
            <select name="deleteuser" id="deleteuser" class="FormArticle-box-input FormCategorySelect">
                <option value="1">Supprimer toutes les données de l'utilisateur</option>
                <option value="2">Supprimer l'utilisateur en gardant ses articles</option>
            </select>
        </div>
        <div class="Form-box-div">
            <input type="hidden" name="token" value="<?=UserSession::token();?>">
        </div>
        <div class="FormCategory-button">
            <button id="deleteUser"  class="FormArticle-box-button" type="submit">Supprimer le membre</button>
        </div>
    </form>

</div>

<script src="<?= asset('js/adminuser.js');?>"></script>
