<?php use App\Framework\UserSession;?>


<?php if (!empty($article)):?>

    <div class="Article">
        <h3 class="Article-title"><?=htmlspecialchars($article['title']);?></h3>

        <?php if(!empty($article['image'])):?>

            <div class="Article-box">
                <img  class="Article-box-img"src="<?=asset('img/' . $article['image']);?>" alt="">
            </div>

        <?php endif;?>

        <p class="Article-content"><?=$article['content'];?></p>



        <p class="Article-pseudo">Écrit par : <?=htmlspecialchars($article['pseudo']);?></p>
        <p class="Article-date">Publié le : <?= (new DateTimeImmutable($article['creation_date']))->format('d/m/Y');?> à <?= (new DateTimeImmutable($article['creation_date']))->format('H:i');?></p>
        <p class="Article-category">Catégorie : <a class="Article-category-link" href="<?=buildUrl('category', ['id'=> intval($article['category_id'])]);?>"><?=htmlspecialchars($article['category']);?></a></p>
    </div>

    <hr>

    <div class="Comments">

    <?php if (UserSession::author() || UserSession::administrator()):?>

        <div class="FormComment">
            <form class="FormComment-box" method="POST" action="<?=buildUrl('addcomment', ['id' => intval($article['id'])]);?>">
                <label class="FormComment-box-label" >Ajouter un commentaire :</label>
                <textarea class="FormComment-box-textarea" type="text" name="comment" id=""></textarea>
                <div class="FormComment-box-buttonBox">
                    <button class="FormComment-box-button" type="submit" name="validate" >Ajouter un commentaire</button>
                </div>
            </form>
        </div>


    <?php else:?>

        <p>Afin de laisser un commentaire, vous devez vous inscrire, ou vous connecter.</p>

    <?php endif;?>

    <hr>

    <h4>Commentaires</h4>

    <?php if (!empty($comments)):?>

        <?php foreach ($comments as $comment):?>

            <div class="Comment-list">
                <p><?= $comment['content'];?></p>
                <p>Écrit par : <?= htmlspecialchars($comment['pseudo']);?></p>
                <p>Publié le : <?=(new DateTimeImmutable($comment['date_publication']))->format('d/m/Y');?></p>
            </div>

        <?php endforeach;?>

    <?php endif;?>

    </div>

<?php endif;?>