<?php use App\Framework\UserSession;?>

<?php if (!empty($article)):?>

    <article class="Article">

        <h3 class="Article-title"><?=htmlspecialchars($article['title']);?></h3>

        <?php if(!empty($article['image'])):?>

            <div class="Article-box">
                <img  class="Article-box-img"src="<?=asset('img/imgArticle/' . $article['image']);?>" alt="<?=$article['image'];?>">
            </div>

        <?php endif;?>

        <p class="Article-content"><?=$article['content'];?></p>
        <p class="Article-pseudo">Écrit par : <?=htmlspecialchars($article['pseudo']);?></p>
        <p class="Article-date">Publié <?= $article['creation_date'];?></p>
        <p class="Article-category">Catégorie : <a class="Article-category-link" href="<?=buildUrl('category', ['id'=> intval($article['category_id'])]);?>"><?=htmlspecialchars($article['category']);?></a></p>

    </article>

    <hr>

    <div class="Comments">

        <?php if (UserSession::author() || UserSession::administrator()):?>

            <div class="FormComment">

                <form class="FormComment-box" method="POST" action="<?=buildUrl('addcomment');?>">

                    <label class="FormComment-box-label" for="comment">Ajouter un commentaire :</label>
                    <textarea class="FormComment-box-textarea" name="comment" id="comment"></textarea>

                    <input type="hidden" name="article-id" value="<?=intval($article['id']);?>">

                    <div class="FormComment-box-buttonBox">
                        <button class="FormComment-box-button" type="submit" name="validate" >Ajouter un commentaire</button>
                    </div>

                </form>

            </div>


        <?php else:?>

            <p>Afin de laisser un commentaire, vous devez vous inscrire, ou vous connecter.</p>

        <?php endif;?>

        <hr>

        <h4>Commentaires</h4>

        <?php if (!empty($comments)):?>

            <?php foreach ($comments as $comment):?>

                <div class="Comment-list">
                    <p class="Comment-content"><?= htmlspecialchars($comment['content']);?></p>
                    <p>Écrit par : <?= htmlspecialchars($comment['pseudo']);?></p>
                    <p>Publié <?=$comment['date_publication'];?></p>
                </div>

            <?php endforeach;?>

        <?php endif;?>

    </div>

<?php endif;?>