<?php use App\Framework\FlashBag;?>

<!DOCTYPE html>
<html lang="fr">
<head>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='http://fonts.googleapis.com/css?family=Lato:400,700,900,300' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,800,600,300' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="<?=asset('css/style.css');?>">
    <link rel="stylesheet" href="<?=asset('css/table.css');?>">
    <link rel="stylesheet" href="<?=asset('css/header.css');?>">
    <link rel="stylesheet" href="<?=asset('css/footer.css');?>">
    <link rel="stylesheet" href="<?=asset('css/forum.css');?>">
    <link rel="stylesheet" href="<?=asset('css/article.css');?>">
    <script src="<?=asset('js/tinymce/js/tinymce/tinymce.min.js');?>"></script>
    <script src="https://cdn.tiny.cloud/1/nsjbtpknw22gfqakd09e980h6d6hin28dwzelpv03mcupto7/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <script>tinymce.init({selector:'#textarea', language : "fr_FR", height: 500});</script>
    <title>Huma Scientio - <?=$pageTitle??'';?></title>

</head>
    <body class="Body">

        <?php require TEMPLATE_DIR . '/header.phtml';?>

        <main class="Body-main">

            <aside class="body-main-aside">
                <?php if (FlashBag::hasMessages('error')):?>
                    <?php foreach (FlashBag::fetchMessages('error') as $error):?>
                        <p class="Message Error-message"><?=htmlspecialchars($error);?></p>
                    <?php endforeach; ?>
                <?php endif; ?>

                <?php if (FlashBag::hasMessages('success')):?>
                    <?php foreach (FlashBag::fetchMessages('success') as $message):?>
                        <p class="Message Success-message"><?=htmlspecialchars($message);?></p>
                    <?php endforeach; ?>
                <?php endif; ?>

                <?php if (FlashBag::hasMessages('query')):?>
                    <?php foreach (FlashBag::fetchMessages('query') as $message):?>
                        <p class="Message Query-message"><?=htmlspecialchars($message);?></p>
                    <?php endforeach; ?>
                <?php endif; ?>
            </aside>

            <?php include TEMPLATE_DIR . '/' . $template . '.phtml'; ?>
        
        </main>

        <?php require TEMPLATE_DIR . '/footer.phtml';?>

        <script type="module" src="<?=asset('js/main.js');?>"></script>
    </body>
</html>