<h3 class="Title"> Catégories </h3>

<?php if (!empty($categories)):?>

    <div class="container">

        <div class="List">

        <?php foreach ($categories as $categorie):?>

            <a class="List-link" href="<?=buildUrl('category', ['id' => intval($categorie['id'])]);?>"><?=htmlspecialchars($categorie['category']);?></a>

        <?php endforeach;?>

        </div>

    </div>

<?php endif;?>





