<div class="Forum-list">

    <?php if (!empty($articlesByCategory)):?>

        <h3 class="TitlePage">Categorie : <?= $articlesByCategory[0]['category'];?></h3>

        <?php foreach ($articlesByCategory as $articleByCategory):?>

            <div class="Forum-list-article">
                <h3 class="Forum-list-article-title"><?= htmlspecialchars($articleByCategory['title']);?></h3>
                <p class="Forum-list-article-content"><?=substr($articleByCategory['content'], 0, 110);?> <span>[...]</span> </p>
                <p class="Forum-list-article-pseudo">Écrit par : <?= htmlspecialchars($articleByCategory['pseudo']);?></p>
                <p class="Forum-list-article-date">Date de publication : <?= $articleByCategory['creation_date'];?></p>
                <p class="Forum-list-article-category">Catégorie : <a class="Forum-list-article-category-link" href="<?=buildUrl('category', ['id' => intval($articleByCategory['id_category'])]);?>"><?=htmlspecialchars($articleByCategory['category']);?></a></p>
                <a class="Forum-list-article-link" href="<?= buildUrl('article', ['id' => intval($articleByCategory['id_article'])]);?>">Lire la suite</a>
            </div>

        <?php endforeach;?>

    <?php endif;?>

</div>