<h3>Changer le mot de passe</h3>

<div class="Form">

    <form class="Form-box" method="POST" action="">
        <div class="Form-box-div">
            <label class="Form-box-label" for="email">Votre e-mail : </label>
            <input type="email" class="Form-box-input" name="email" id="email" value="<?=htmlspecialchars($email);?>">
        </div>
        <div class="Form-box-div">
            <label for="newPassword" class="Form-box-label">Nouveau mot de passe :</label>
            <input type="password" id="newPassword" class="Form-box-input" required name="newPassword">
        </div>
        <div class="Form-box-div">
            <label for="confirmNewPassword" class="Form-box-label">Confirmer le nouveau mot de passe :</label>
            <input type="password" class="Form-box-input" required name="confirmNewPassword" id="confirmNewPassword">
        </div>
        <div class="Form-box-div">
            <label for="keyReinitialization" class="Form-box-label">Clé de modification :</label>
            <input type="password" class="Form-box-input" name="keyReinitialization" id="keyReinitialization">
        </div>
        <div class="Form-box-div">
            <input type="submit" class="Form-box-button" value="Changer le mot de passe" />
        </div>
    </form>
    
</div>