<footer class="Footer">
    
    <section class="Footer-box">

        <div class="Footer-box-section1">
            <h4 class="Footer-box-section1-title">À propos</h4>
            <p class="Footer-box-section1-informations">Huma Scientio est un site de diffusion de contenus pédagogiques et de contributions individuelles ou collectives ayant pour thématique les sciences humaines.</p>
        </div>

        <div class="Footer-box-section2">
            <div class="Footer-box-section2-left">
                <h4 class="Footer-box-section2-title">Menu</h4>
                <a href="<?=buildUrl('homepage');?>" class="Footer-box-section2-link">Accueil</a>
                <a href="<?=buildUrl('forum');?>" class="Footer-box-section2-link">Forum</a>
                <a href="<?=buildUrl('categories');?>" class="Footer-box-section2-link">Catégories</a>
            </div>
            <div class="Footer-box-section2-right">
                <h4 class="Footer-box-section2-title">Liens</h4>
                <a href="#" class="Footer-box-section2-link">Contact</a>
            </div>
        </div>

    </section>
        <div class="Footer-box-hr">
            <hr>
        </div>
        <p class="Footer-box-copyrights">Nicolas SANNA 2021 -  Tous droits réservés ©</p>
</footer>
