<h2 class="Forum-h2">Forum des Articles</h2>
<ul class="ListeArticles-ul">
    <?php foreach ($articles as $article): ?>
        <li class="ListeArticles-li">
            <h3 class="ListeArticles-h3"><?=$article['nom_article'];?></h3>
            <p class="ListeArticles-date">Date de création : <?=(new DateTimeImmutable($article['date_creation_article']))->format('d/m/Y');?></p>
            <div class="ListeArticles-contenu"><?=mb_substr($article['contenu'],0,150);?> [...] </div>
            <a class="ListeArticles-suite" href="/article?id=<?=$article['id_art'];?>">Lire la suite</a>
        </li>
    <?php endforeach; ?>
</ul>  