<?php use App\Framework\UserSession;?>

<header class="Header">
    
    <div class="Header-container">
        <!-- Effet Brouillard -->
        <div id="foglayer_01" class="fog">
            <div class="image01"></div>
            <div class="image02"></div>
        </div>
        <div id="foglayer_02" class="fog">
            <div class="image01"></div>
            <div class="image02"></div>
        </div>
        <div id="foglayer_03" class="fog">
            <div class="image01"></div>
            <div class="image02"></div>
        </div>
        <!--  -->
        <div class="Header-container-">
            <div class="Header-container-box">
                <h1 class="Header-container-box-h1">Huma Scientio</h1>
                <p class="Header-container-box-p">Les Voyages du Temps et de l'Esprit</p>
                <a class ="Header-container-box-a" href="<?=buildUrl('forum');?>"> Voir nos derniers articles</a>
            </div>      
        </div>
    </div>

    <nav class="Header-navbarbox">

        <div class="Header-navbarbox-burgerBox">
            <span class="Header-navbarbox-burgerBox-burger" id="burger">☰</span>
            <span class="Header-navbarbox-burgerBox-cross" id="cross">✖</span>
        </div>

        <div class ="Header-navbarbox-navbar">

            <ul class="Header-navbarbox-navbar-ul">

                <li>
                    <a class="Header-navbarbox-navbar-ul-a" href="<?=buildUrl('homepage');?>">Accueil</a>
                </li>
                <li>
                    <a class="Header-navbarbox-navbar-ul-a" href="<?=buildUrl('forum');?>">Forum</a>
                </li>
                <li>
                    <a class="Header-navbarbox-navbar-ul-a" href="<?=buildUrl('categories');?>">Catégories</a>
                </li>
                <li>
                    <a class="Header-navbarbox-navbar-ul-a" href="<?= buildUrl('search');?>">Rechercher</a>
                </li>
                
                <?php if (!UserSession::isAuthenticated()): ?>

                    <li>
                        <a class="Header-navbarbox-navbar-ul-a" href="<?=buildUrl('connexion');?>">Connexion</a>
                    </li>
                    
                    <li>
                        <a class="Header-navbarbox-navbar-ul-a" href="<?=buildUrl('signup');?>">Créer un compte</a>
                    </li>
                
                <?php else: ?>

                    <li>
                        <span class="Header-navbarbox-navbar-ul-a">–</span>
                    </li>
                    
                    <li>
                        <span class="Header-navbarbox-navbar-ul-a"> Bienvenue <?=UserSession::getUserFullname();?></span>
                    </li>

                    <li>                      
                        <a class="Header-navbarbox-navbar-ul-a" href="<?=buildUrl('administration');?>">Administration</a>
                    </li>    

                    <li>                       
                        <a class="Header-navbarbox-navbar-ul-a" href="<?=buildUrl('deconnexion');?>">Déconnexion</a>
                    </li>

                <?php endif;?>

            </ul>

        </div>

    </nav>

</header>
