<h2 class="TitlePage">Bienvenue sur Huma Scientio</h2>

<div class="HomePage">

    <video controls playsinline autoplay muted loop class="HomePage-video">
        <source src="<?= asset('img/production-ID_4205790.mp4');?>">
    </video>

    <section class="HomePage-section">

        <hr>

        <?php if (!empty($articles)):?>

            <h3 class="HomePage-section-h3">Nos deux derniers articles</h3>

            <?php foreach ($articles as $article):?>

                <div class="HomePage-section-list-article">
                    <h3 class="HomePage-section-list-article-title"><?=htmlspecialchars($article['title']);?></h3>
                    <p class="HomePage-section-list-article-pseudo">Écrit par : <?= htmlspecialchars($article['pseudo']);?></p>
                    <p class="HomePage-section-list-article-date">Date de publication : <?= $article['creation_date'];?></p>
                    <p class="HomePage-section-list-article-category">Catégorie : <a class="Forum-list-article-category-link" href="<?= buildUrl('category', ['id'=> intval($article['category_id'])]);?>"><?= htmlspecialchars($article['category']);?></a></p>
                    <a class="LinkA" href="<?= buildUrl('article', ['id' => intval($article['id'])]);?>">Lire l'article</a>
                </div>

                <hr>

            <?php endforeach;?>

        <?php else:?>

            <p>Il n'y a encore aucun article.</p>

        <?php endif;?>

    </section>

</div>

<div class="Home">

    <section class="Home-section">

        <h3 class="Home-section-h3">Présentation</h3>
        <p>Aliquam at fringilla felis. Sed in sem a risus fermentum ullamcorper et eget purus. Praesent gravida turpis vitae lobortis dapibus. In quis magna id arcu elementum eleifend lobortis sit amet ante. Aliquam blandit risus ut orci maximus luctus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas vulputate dapibus molestie. Sed justo orci, porttitor vel eros faucibus, viverra fringilla mauris. Mauris interdum, ante a viverra consectetur, nibh massa aliquet enim, in semper ligula massa id justo. Sed dapibus, nisi a sodales scelerisque, enim est luctus ligula, vitae porta neque lacus ac risus. Aliquam ac nunc pretium, interdum dui in, pretium ipsum. Etiam ut dui et felis commodo dictum nec dapibus neque. Morbi posuere libero ut ante malesuada placerat. Phasellus iaculis rhoncus nunc, ac commodo tortor.
        Morbi ornare tempus metus, id vestibulum orci sagittis at. Suspendisse pellentesque sem et varius cursus. Quisque dolor mi, maximus id tortor eget, sagittis sagittis felis. Fusce non condimentum felis.</p>

    </section>

</div>