<h2 class="TitlePage">Bienvenue sur Huma Scientio</h2>

<div class="HomePage">

    <video controls playsinline autoplay muted loop class="HomePage-video">
        <source src="<?= asset('img/production-ID_4205790.mp4');?>">
    </video>

    <section class="HomePage-section">

        <hr>

        <?php if (!empty($articles)):?>

            <h3 class="HomePage-section-h3">Nos derniers articles</h3>

            <?php foreach ($articles as $article):?>

                <div class="HomePage-section-list-article">
                    <h3 class="HomePage-section-list-article-title"><?=htmlspecialchars($article['title']);?></h3>
                    <p class="HomePage-section-list-article-pseudo">Écrit par : <?= htmlspecialchars($article['pseudo']);?></p>
                    <p class="HomePage-section-list-article-date">Date de publication : <?= $article['creation_date'];?></p>
                    <p class="HomePage-section-list-article-category">Catégorie : <a class="Forum-list-article-category-link" href="<?= buildUrl('category', ['id'=> intval($article['category_id'])]);?>"><?= htmlspecialchars($article['category']);?></a></p>
                    <a class="LinkA" href="<?= buildUrl('article', ['id' => intval($article['id'])]);?>">Lire l'article</a>
                </div>

                <hr>

            <?php endforeach;?>

        <?php else:?>

            <p>Il n'y a encore aucun article.</p>

        <?php endif;?>

    </section>

</div>

<div class="Home">

    <section class="Home-section">

        <h3 class="Home-section-h3">Présentation</h3>
        <p> « La forme intelligible de la science est la voie vers elle qui est ouverte et offerte à tous et rendue la même pour tous ». C'est dans l'état d'esprit de cette phrase de Hegel issue de la Phénoménologie de l'Esprit que s'inscrit le projet de ce site : rendre accessible à toutes et à tous un ensemble riche et structuré d'articles et de documents en rapport avec toutes les sciences humaines : Histoire, Philosophie, Économie, Sociologie, Anthropologie, Psychologie, Art, et encore d'autres domaines. </p>
        
        <p>La possibilité de rendre consultable l'ensemble de ces publications est un souhait qui tenait à cœur au créateur de ce site dont l'ambition est de permettre à des néophytes de pouvoir mieux s'y retrouver et d'obtenir des articles de qualité structurés et compréhensibles destinés à toutes et à tous.</p>
        
        <p>La connaissance est une grande aventure humaine que nous sommes prêts à partager avec vous !</p>

    </section>

</div>