<?php if (!App\Framework\UserSession::isAuthenticated()):?>

<h3 class="Form-title">Inscription</h3>

<div class="Form">
    <form class="Form-box" method="POST">
        <label for="lastname" class="Form-box-label">Nom :</label>
        <input type="text" class="Form-box-input" name="lastname" value="<?=$lastname;?>">

        <label for="firstname" class="Form-box-label">Prénom :</label>
        <input type="text" class="Form-box-input" name="firstname" value="<?=$firstname;?>">

        <label for="pseudo" class="Form-box-label">Pseudo (il sera visible sur tout le site) :</label>
        <input type="text" class="Form-box-input" name="pseudo" value="<?=$pseudo;?>">

        <label for="email" class="Form-box-label">E-mail : </label>
        <input type="email" class="Form-box-input" name="email" value="<?=$email;?>">

        <label for="password" class="Form-box-label">Mot de passe :</label>
        <input type="password" id="password" class="Form-box-input" required name="password">

        <label for="password" class="Form-box-label">Voir le mot de passe</label>
        <input type="checkbox" class="Form-box-input" id="viewPassword" name="viewPassword">

        <label for="password" class="Form-box-label">Confirmer le mot de passe :</label>
        <input type="password" class="Form-box-input" required name="confirmPassword">
        
        <button type="submit" class="Form-box-button" name="validate">S'inscrire</button>
        <a class="Link" href="<?= buildUrl('connexion');?>">J'ai déjà un compte, je me connecte</a>
    </form>

</div>

<?php else :?>

    <p> Vous êtes déjà connecté. </p>

<?php endif;?>

<script src="<?=asset('js/inscription.js');?>"></script>