<?php if (!App\Framework\UserSession::isAuthenticated()):?>

<h3 class="Form-title">Connexion</h3>
<div class="Form">
    <form class="Form-box" method="POST">

        <label class="Form-box-label" for="email">Votre e-mail : </label>
        <input type="email" class="Form-box-input" name="email" id="email" value="<?=$email;?>">

        <label for="password" class="Form-box-label">Votre mot de passe : </label>
        <input type="password" class="Form-box-input" name="password" id="password">

        <input type="submit" class="Form-box-button" value="Connexion" />

        <a class="Link" href="<?= buildUrl('signup');?>">Je n'ai pas de compte, je m'inscris</a>

    </form>
    
</div>


<?php else :?>

    <p> Vous êtes déjà connecté. </p>

<?php endif;?>