<?php if (!App\Framework\UserSession::isAuthenticated()):?>

<h3 class="Form-title">Connexion</h3>

<div class="Form">

    <form class="Form-box" method="POST">
        <div class="Form-box-div">
            <label class="Form-box-label" for="email">Votre e-mail : </label>
            <input type="email" class="Form-box-input" name="email" id="email" value="<?=htmlspecialchars($email);?>">
        </div>
        <div class="Form-box-div">
            <label for="password" class="Form-box-label">Votre mot de passe : </label>
            <input type="password" class="Form-box-input" name="password" id="password">
        </div>
            <input type="submit" class="Form-box-button" value="Connexion" />
        <div class="Form-box-div">
            <a class="Link" href="<?= buildUrl('signup');?>">Je n'ai pas de compte, je m'inscris</a>
            <a class="Link" href="<?= buildUrl('sendEmailForgetPassword');?>">Mot de passe oublié ?</a>
        </div>
    </form>
    
</div>

<?php else :?>

    <p> Vous êtes déjà connecté. </p>

<?php endif;?>