<h3 class="Form-title">Modifier le mot de passe</h3>

<div class="Form">
    <form class="Form-box" method="POST">

        <label class="Form-box-label" for="email">Votre e-mail : </label>
        <input type="email" class="Form-box-input" name="email" id="email" value="<?=$email;?>">

        <label for="newPassword" class="Form-box-label">Votre nouveau mot de passe :</label>
        <input type="password" class="Form-box-input" name="newPassword" id="password">

        <label for="confirmNewPassword" class="Form-box-label">Confirmer le nouveau mot de passe :</label>
        <input type="password" class="Form-box-input" name="confirmNewPassword" id="password">

        <input type="submit" class="Form-box-button" value="Changer mon mot de passe" />

    </form>  
</div>

