<h4>Mot de passe oublié ?</h4>

<div class="Form">

    <form class="Form-box" method="POST">
        <div class="Form-box-div">
            <label class="Form-box-label" for="email">Votre e-mail : </label>
            <input type="email" class="Form-box-input" name="email" id="email" value="<?=htmlspecialchars($email);?>">
        </div>
        <div class="Form-box-div">
            <input type="submit" class="Form-box-button" value="Réinitialiser le mot de passe" />
        </div>
        <a class="Link" href="<?= buildUrl('changePassword');?>">Changer le mot de passe</a>
        <a class="Link" href="<?= buildUrl('signup');?>">Je n'ai pas de compte, je m'inscris</a>
    </form>
    
</div>