<h4>Mot de passe oublié ?</h4>

<div class="Form">
    <form class="Form-box" method="POST">

        <label class="Form-box-label" for="email">Votre e-mail : </label>
        <input type="email" class="Form-box-input" name="email" id="email" value="<?=$email;?>">

        <input type="submit" class="Form-box-button" value="Envoyer un email de réinitialisation" />

        <a class="Link" href="<?= buildUrl('changePassword');?>">Changer le mot de passe</a>

        <a class="Link" href="<?= buildUrl('signup');?>">Je n'ai pas de compte, je m'inscris</a>

    </form>
    
</div>