<!--<h4>Envoyer un fichier</h4>

<form action="" method="POST" enctype="multipart/form-data" class="uploadfileform">
    <label for="name">Description</label>
    <input type="text" name="name" id="" value="<?=$name;?>">
    <label for="content">Description</label>
    <textarea name="content" id="" cols="30" rows="10"><?=$content;?></textarea>
    <input type="file" name="image" accept="image/*">
    <input type="submit" value="Envoyer">
</form>-->