<?php use App\Framework\UserSession;?>

<h3>Créer une catégorie</h3>

<form action="" method="POST">
        <label for="newcategory">Créer une catégorie : </label>
        <input type="text" name="newcategory" id="category" value="<?=$newCategory;?>">
        <input type="hidden" name="token" value="<?=UserSession::token();?>">
        <br />
        <input type="submit" value="Créer une catégorie" />
</form>