<?php use App\Framework\UserSession ;?>

<h3>Administration</h3>

<?php if(UserSession::author() || UserSession::administrator()):?>

<p><a href="<?=buildUrl('myarticles');?>">Gérer mes articles</a></p>

<p><a href="<?=buildUrl('newarticle');?>">Créer un article</a></p>

<p><a href="<?=buildUrl('uploadFile');?>">Charger des fichiers</a></p>

<?php endif;?>

<?php if(UserSession::administrator()):?>

    <p><a href="<?=buildUrl('adminusers');?>">Gérer les membres</a></p>

    <p><a href="<?=buildUrl('addCategory');?>">Créer une catégorie</a></p>

    <p><a href="<?=buildUrl('adminCategories');?>">Gérer les catégories</a></p>

    <p><a href="<?=buildUrl('commentsAdministration');?>">Modérer les commentaires</a></p>

<?php endif;?>

<?php if (UserSession::newRegistered()):?>

    <p>Bienvenue nouvel(lle) uutilisateur(trice) ! Veuillez patienter pendant qu'un administrateur vous donne accès à la création de vos articles. </p>

<?php endif;?>