<h1>Gérer les utilisateurs</h1>

<table>
    <thead>
        <tr>
            <th>Identifiant</th>
            <th>Nom</th>
            <th>Prénom</th>
            <th>E-mail</th>
            <th>Pseudo</th>
            <th>Date d'inscription</th>
            <th>Nombre d'articles</th>
            <th>Rôle</th>
            <th colspan="2">Actions</th>
        </tr>
    </thead>
        <tbody>

            <?php if (!empty($usersInfos)):?>

                <?php foreach ($usersInfos as $userInfos):?>

                    <tr>
                        <td><?= htmlspecialchars($userInfos['userId']);?></td>
                        <td><?= ($userInfos['lastname']);?></td>
                        <td><?= htmlspecialchars($userInfos['firstname']);?></td>
                        <td><?= htmlspecialchars($userInfos['email']);?></td>
                        <td><?= htmlspecialchars($userInfos['pseudo']);?></td>
                        <td><?= (new DateTimeImmutable($userInfos['inscription_date']))->format('d/m/Y');?></td>
                        <td><?= $userInfos['number_articles'];?></td>
                        <td><?= htmlspecialchars($userInfos['privilege']);?></td>
                        <td><a id="a-modify" href="<?= buildUrl('modifygrantuser', ['id' => intval($userInfos['userId'])]);?>">Modifier le rôle</a></td>
                        <td><a id="a-delete" href="<?= buildUrl('deleteUser', ['id' => intval($userInfos['userId'])]);?>">Supprimer</a></td>
                    </tr>
                
                <?php endforeach;?>

            <?php endif;?>

        </tbody>
</table>

