<h3>Administration</h3>

<p><a href="<?=buildUrl('myarticles');?>">Gérer mes articles</a></p>

<p><a href="<?=buildUrl('newarticle');?>">Créer un article</a></p>

<?php if(App\Framework\UserSession::administrator()):?>

    <p><a href="<?=buildUrl('adminusers');?>">Gérer les membres</a></p>

    <p><a href="<?=buildUrl('addCategory');?>">Créer une catégorie</a></p>

    <p><a href="<?=buildUrl('adminCategories');?>">Modifier une catégorie</a></p>
<?php endif;?>