<h3>Gérer les catégories</h3>

<table>

    <thead>
        <tr>
            <th>id</th>
            <th>Catégorie</th>
            <th colspan="2">Actions</th>
        </tr>
    </thead>

    <tbody>

        <tr>
            <td>1</td>
            <td>Non classé</td>
            <td>Modifier</td>
            <td>Supprimer</td>
        </tr>

        <?php if(!empty($categories)):?>

            <?php foreach ($categories as $categorie):?>

                <tr>
                    <td><?=$categorie['id'];?></td>
                    <td><?=htmlspecialchars($categorie['category']);?></td>
                    <td><a id="a-modify" href="<?=buildUrl('modifycategory', ['id' => intval($categorie['id'])]);?>">Modifier </a></td>
                    <td><a id="a-delete" href="<?=buildUrl('deletecategory', ['id' => intval($categorie['id'])]);?>">Supprimer</a></td>
                </tr>

            <?php endforeach;?>

        <?php endif;?>

    </tbody>

</table>