<h3>Gérer les catégories</h3>

<table>
    <tr>
        <th>id</th>
        <th>Catégorie</th>
        <th colspan="2">Actions</th>
    </tr>

    <?php if(isset($categories)):?>

       <?php foreach ($categories as $categorie):?>

        <tr>
            <td><?=$categorie['id'];?></td>
            <td><?=$categorie['category'];?></td>
            <!-- A FAIRE -->
            <td><a href="<?=buildUrl('modifycategory', ['id' => intval($categorie['id'])]);?>">Modifier </a></td>
            <td><a href="<?=buildUrl('deletecategory', ['id' => intval($categorie['id'])]);?>">Supprimer</a></td>
        </tr>

        <?php endforeach;?>

    <?php endif;?>
</table>