<h3>Gérer les catégories</h3>

<table>
<thead>
    <tr>
        <th>id</th>
        <th>Catégorie</th>
        <th colspan="2">Actions</th>
    </tr>
    </thead>
    <tbody>
    <?php if(isset($categories)):?>

       <?php foreach ($categories as $categorie):?>

            <tr>
                <td><?=$categorie['id'];?></td>
                <td><?=htmlspecialchars($categorie['category']);?></td>
                <!-- A FAIRE -->
                <td><a href="<?=buildUrl('modifycategory', ['id' => intval($categorie['id'])]);?>">Modifier </a></td>
                <td><a href="<?=buildUrl('deletecategory', ['id' => intval($categorie['id'])]);?>">Supprimer</a></td>
            </tr>

        <?php endforeach;?>

    <?php endif;?>
    </tbody>
</table>