<h3>Supprimer l'utilisateur <?= htmlspecialchars($userInfos['pseudo']);?></h3>

<form method="POST">
    <select name="deleteuser">
        <option value="1">Supprimer toutes les données de l'utilisateur</option>
        <option value="2">Supprimer l'utilisateur mais conserver ses articles et commentaires</option>
    </select>
    <button id="deleteUser" type="submit">Supprimer</button>
</form>

