<h3 class="TitlePage">Supprimer la catégorie : <?= htmlspecialchars($category['category']);?> </h3>

<div class="Form">
    <form class="Form-box" method="POST">
        <label class="Form-box-label" name="deleteCategory" ></label>
        <select name="deleteCategory" class="FormArticle-box-input FormCategorySelect">
            <option value="1">Supprimer la catégorie et ses articles associés</option>
            <option value="2">Supprimer la catégorie en conservant les articles</option>
        </select>
        <div class="FormCategory-button">
            <button id="deleteCategory"  type="submit" class="FormArticle-box-button" type="submit">Supprimer</button>
        </div> 
    </form>
</div>

