<?php use App\Framework\UserSession;?>

<h3 class="TitlePage">Modifier l'article</h3>

<div class="Article-box">
    <?php if(!empty($imageExist)):?>
        <img  class="Article-box-img"src="<?=asset('img/imgArticle/' . $imageExist);?>" alt="">
    <?php else:?>
        <img  class="Article-box-img"src="#" alt="">
    <?php endif;?>
</div>

<div class="FormArticle">

    <form class="FormArticle-box" method="POST" id="formArticle" enctype="multipart/form-data" action="">

        <label for="title"  class="FormArticle-box-label">Titre de l'article :</label>
        <input class="FormArticle-box-input" name="title" value="<?=$title;?>"></input>

        <label for="content" class="FormArticle-box-label">Contenu de l'article : </label>
        <textarea class="FormArticle-box-textarea" id="textarea" name="content" ><?=$content;?></textarea>

        <input type="hidden" name="token" value="<?=UserSession::token();?>">

        <label for="categories" class="FormArticle-box-select">Catégorie :</label>
        <select name="categories" id="categories" class="FormArticle-box-input FormArticleSelect" id="">
            <?php foreach ($categories as $category):?>
                <?php $selected = isset($selectedCategory) && $category['id'] == $selectedCategory ? 'selected' : '';?>
                <option <?=$selected;?> value="<?= $category['id'];?>" ><?= htmlspecialchars($category['category']);?></option>
            <?php endforeach;?>
        </select>

        <?php if(!empty($imageExist)):?>
            <a class="LinkA" href="<?=buildUrl('deleteImage', ['id' => intval($idOfArticle)]);?>">Supprimer l'image d'arrière-plan</a>
        <?php endif;?>

        <div class="parent-div">
            <button class="btn-upload">Choisir l'image d'arrière plan</button>
            <input type="file" class="FormArticle-box-input" name="image" id="upload" accept="image/*, .png, .jpg, .jpeg">
        </div>

        <div class="FormArticle-button">
            <button type="submit" class="FormArticle-box-button" name="validate">Modifier l'article</button>
        </div> 

    </form>

</div>


<script src="<?=asset('js/upload.js');?>"></script>
<script src="<?=asset('js/uploadImage.js');?>"></script>