<h3 class="TitlePage">Modifier l'article</h3>

    <?php if(!empty($imageExist)):?>
       
        <div class="Article-box">
            <h4>Image actuelle :</h4>
            <img  class="Article-box-img"src="<?=asset('img/' . $imageExist);?>" alt="">
        </div>

    <?php endif;?>

<div class="FormArticle">
    <form class="FormArticle-box" method="POST" id="formArticle" enctype="multipart/form-data">
        <label for="title"  class="FormArticle-box-label">Titre de l'article :</label>
        <input  name="title" class="FormArticle-box-input" value="<?=$title;?>"></input>
        <label for="content" class="FormArticle-box-label">Contenu de l'article : </label>
        <textarea class="FormArticle-box-textarea" id="textarea" name="content" ><?=$content;?></textarea>
        <label for="title" class="FormArticle-box-select">Catégorie :</label>
            <select name="categories" class="FormArticle-box-input FormArticleSelect" id="">
                <?php foreach ($categories as $category):?>
                    <option value="<?= $category['id'];?>" ><?= htmlspecialchars($category['category']);?></option>
                <?php endforeach;?>
            </select>
                <?php if(!empty($imageExist)):?>
                    <a class="LinkAForm" href="<?=buildUrl('deleteImage', ['id' => intval($idOfArticle)]);?>">Supprimer l'image d'arrière-plan</a>
                <?php endif;?>
            <label for="title" class="FormArticle-box-label">Changer ou ajouter une image :</label>
            <input type="file" class="FormArticle-box-input File" name="image" id="upload" accept="image/*">
        <div class="FormArticle-button">
            <button type="submit" class="FormArticle-box-button" name="validate">Modifier l'article</button>
        </div> 
    </form>
</div>

<script src="<?=asset('js/upload.js');?>"></script>
