<?php use App\Framework\UserSession;?>

<h3 class="TitlePage">Mes articles</h3>

<p><a class="Link" href="<?=buildUrl('newarticle');?>">Créer un article</a></p>

<table>
    <thead>
        <tr>
            <th>Id</th>
            <th>Titre</th>
            <th>Date de création</th>
            <th>Catégorie</th>
            <th>Commentaires</th>
            <th colspan="2">Actions</th>
        </tr>
    </thead>
    <tbody>

        <?php if (!empty($myArticles)):?>

            <?php foreach ($myArticles as $myArticle):?>

                <tr>
                    <td><?=$myArticle['articleId'];?></td>
                    <td> <a href="<?=buildUrl('article', ['id' => intval($myArticle['articleId'])]);?>"><?=htmlspecialchars(substr($myArticle['title'], 0, 100));?> [...]</a></td>
                    <td><?=(new DateTimeImmutable($myArticle['creation_date']))->format('d/m/Y');?></td>
                    <td><a href="<?=buildUrl('category', ['id' => intval($myArticle['category_id'])]);?>"><?=$myArticle['category'];?></a></td>
                    <td><?=$myArticle['number_comments'];?></td>
                    <td><a id="a-modify" href="<?=buildUrl('modifyarticle', ['id' => intval($myArticle['articleId'])]);?>">Modifier</a></td>
                    <td><a id="a-delete" class="deleteArticle" href="<?=buildUrl('deletearticle', ['id' => intval($myArticle['articleId']), 'token' => UserSession::token()]);?>">Supprimer</a></td>
                </tr>

            <?php endforeach;?>

        <?php else:?>

            <p>Vous n'avez publié aucun article.</p>

        <?php endif;?>
        
    </tbody>
</table>

<script src="<?= asset('js/adminarticle.js');?>"></script>