<h3>Publier un article</h3>

<div class="FormArticle">
    <form class="FormArticle-box" method="POST" enctype="multipart/form-data">
        <label for="title" class="FormArticle-box-label">Titre de l'article :</label>
        <input  name="title" class="FormArticle-box-input" value="<?=$title;?>"></input>
        <label for="content" class="FormArticle-box-label">Contenu de l'article : </label>
        <textarea class="FormArticle-box-textarea" id='textarea' name="content" ><?=$content;?></textarea>
        <label for="title" class="FormArticle-box-select">Catégorie :</label>
        <select name="categories" class="FormArticle-box-input FormArticleSelect" id="">
            <?php foreach ($categories as $category):?>
                <option value="<?= $category['id'];?>" ><?= htmlspecialchars($category['category']);?></option>
            <?php endforeach;?>
        </select>
        <label for="title" class="FormArticle-box-label">Ajouter une image :</label>
        <input type="file" class="FormArticle-box-input File" name="image" id="" accept="image/*">
        <div class="FormArticle-button">
            <button type="submit" class="FormArticle-box-button" name="validate">Publier l'article</button>
        </div>
    </form>
</div>




