<?php use App\Framework\UserSession;?>

<h3>Publier un article</h3>

<div class="Article-box">
    <img class="Article-box-img" src="#" alt="">
</div>

<div class="FormArticle">

    <form class="FormArticle-box" method="POST" id="formArticle" enctype="multipart/form-data" action=""> 

        <div class="FormArticle-box-div">
            <label for="title" class="FormArticle-box-label">Titre de l'article :</label>
            <input  class="FormArticle-box-input" name="title" value="<?=htmlspecialchars($title);?>"></input>
        </div>
        <div class="FormArticle-box-div">
            <label for="content" class="FormArticle-box-label">Contenu de l'article : </label>
            <textarea class="FormArticle-box-textarea" id='textarea' name="content" ><?=htmlspecialchars($content);?></textarea>
        </div>
        <div class="FormArticle-box-div">
            <label for="categories" class="FormArticle-box-select">Catégorie :</label>
            <select class="FormArticle-box-input FormArticleSelect" id="categories" name="categories" >
                <?php foreach ($categories as $category):?>
                    <?php $selected = isset($selectedCategory) && $category['id'] == $selectedCategory ? 'selected' : '';?>
                    <option <?=$selected;?> value="<?= $category['id'];?>" ><?= htmlspecialchars($category['category']);?></option>
                <?php endforeach;?>
            </select>
        </div>
        <div class="FormArticle-box-div">
            <input type="hidden" name="token" value="<?=UserSession::token();?>">
        </div>
        <div class="parent-div">
            <button class="btn-upload">Choisir l'image d'arrière plan</button>
            <input type="file" class="FormArticle-box-input" name="image" id="upload" accept="image/*">
        </div> 
        <div class="FormArticle-button">
            <button type="submit" class="FormArticle-box-button" name="validate">Publier l'article</button>
        </div>

    </form>

</div>

<script src="<?=asset('js/upload.js');?>"></script>
<script src="<?=asset('js/uploadImage.js');?>"></script>




