<?php use App\Framework\UserSession;?>


<?php if (isset($article)):?>

    <div class="Article">

        <h3 class="Article-title"><?=htmlspecialchars($article['title']);?></h3>

        <p class="Article-content"><?=($article['content']);?></p>

        <p class="Article-pseudo">Écrit par : <?=htmlspecialchars($article['pseudo']);?></p>

        <p class="Article-date">Publié le : <?= (new DateTimeImmutable($article['creation_date']))->format('d/m/Y');?> à <?= (new DateTimeImmutable($article['creation_date']))->format('H:i');?></p>

        <p class="Article-category">Catégorie : <a class="Article-category-link" href="<?=buildUrl('category', ['id'=> intval($article['category_id'])]);?>"><?=htmlspecialchars($article['category']);?></a></p>

    </div>

    <div class="Comments">

    <?php if (UserSession::author() || UserSession::administrator()):?>

        <h4>Ajouter un commentaire</h4>

        <form method="POST" action="<?=buildUrl('addcomment', ['id' => intval($article['id'])]);?>">
            <label >Ajouter un commentaire :</label>
            <textarea type="text" name="comment" id=""></textarea>
            <button type="submit" name="validate" >Ajouter un commentaire</button>
        </form>

    <?php else:?>

        <p>Afin de laisser un commentaire, vous devez vous inscrire, ou vous connecter.</p>

    <?php endif;?>

    <hr>

    <h4>Commentaires</h4>

    <?php if (isset($comments)):?>

        <?php foreach ($comments as $comment):?>

            <p><?=$comment['content'];?></p>
            <p>Écrit par : <?=$comment['pseudo'];?></p>
            <p>Publié le : <?=(new DateTimeImmutable($comment['date_publication']))->format('d/m/Y');?></p>

            <hr>

        <?php endforeach;?>

    <?php endif;?>

    </div>

<?php endif;?>