<?php use App\Framework\UserSession;?>
<?php use App\Framework\FlashBag;?>

<!DOCTYPE html>
<html lang="fr">
<head>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='http://fonts.googleapis.com/css?family=Lato:400,700,900,300' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,800,600,300' rel='stylesheet' type='text/css'>
    <title><?=$pageTitle??'';?></title>
    <link rel="stylesheet" href="<?=asset('css/style.css');?>">

</head>
<body class="Body">

    <?php require TEMPLATE_DIR . '/header.phtml';?>

    <main class="Body-main">

        <aside class="body-main-aside">
            <?php if (FlashBag::hasMessages('error')):?>
                <?php foreach (FlashBag::fetchMessages('error') as $error):?>
                    <p class="message error-message"><?=htmlspecialchars($error);?></p>
                <?php endforeach; ?>
            <?php endif; ?>

            <?php if (FlashBag::hasMessages('success')):?>
                <?php foreach (FlashBag::fetchMessages('success') as $message):?>
                    <p class="message success-message"><?=htmlspecialchars($message);?></p>
                <?php endforeach; ?>
            <?php endif; ?>
        </aside>

        <?php include TEMPLATE_DIR . '/' . $template . '.phtml'; ?>
    
    </main>

    <?php require TEMPLATE_DIR . '/footer.phtml';?>

    <script src="<?=asset('js/app.js');?>"></script>

    <?php if (UserSession::isAuthenticated()):?>
        
        <script src="<?=asset('js/adminuser.js');?>"></script>
        <script src="<?=asset('js/admincategory.js');?>"></script>
        <script src="<?=asset('js/adminarticle.js');?>"></script>
        
    <?php endif;?>
</body>
</html>