<h1 class="Forum-h1">Forum des articles</h1>

<div class="Forum-list">

    <?php if (isset($articles)):?>

        <?php foreach ($articles as $article):?>

            <div class="Forum-list-article">

                <h3 class="Forum-list-article-title"><?=htmlspecialchars($article['title']);?></h3>

                <p class="Forum-list-article-content"><?=mb_substr($article['content'], 0, 150);?> [...] </p>

                <p class="Forum-list-article-pseudo">Écrit par : <?=htmlspecialchars($article['pseudo']);?></p>

                <p class="Forum-list-article-date">Date de publication : Le <?= (new DateTimeImmutable($article['creation_date']))->format('d/m/Y');?> à <?= (new DateTimeImmutable($article['creation_date']))->format('h:i');?></p>

                <p class="Forum-list-article-category">Catégorie : <a class="Forum-list-article-category-link" href=""><?=htmlspecialchars($article['category']);?></a></p>

                <a class="Forum-list-article-link" href="<?=buildUrl('article', ['id' => intval($article['id'])]);?>">Lire la suite</a>

            </div>

        <?php endforeach;?>

    <?php endif;?>

</div>
