<?php if (isset($articleInfos)):?>
  <div class="">
    <div class="">
      <div class="">
        <h5 class=""><?=$articleInfos['title'];?></h5>
          <br>
            <p class=""><?=$articleInfos['content'];?></p>
            <p class="">Écrit par : <?=$articleInfos['pseudo'];?></small></p>
            <p class="">Catégorie : <a href="<?=buildUrl('categorie', ['id' => intval($articleInfos['category_id'])]);?>"><?= $articleInfos['category'] ;?></a>
            <p class="">Publié le : <?= (new DateTimeImmutable($articleInfos['creation_date']))->format('d/m/Y') ;?></small></p>
        </div>
      </div>
    </div>
<?php endif;?>

    <?php if(isset($_SESSION['auth'])):?>

      <section class="">
        <form class="" method="POST">
            <div class="">
                <label for="" class="">Commentaire : </label>
                <textarea name="answer" class=""></textarea>

                <button class="btn btn-primary" type="submit" name="validate">Laisser un commentaire</button>
            </div>
        </form>
      </section>

    <?php else :?>

      <p class=""> Afin de laisser un commentaire, vous devez vous inscrire ou vous connecter. </p>

    <?php endif;?>

  <h5 class="">Commentaires</h5>
  <?php if (isset($CommentsOfThisArticle)):?>
    <?php foreach ($CommentsOfThisArticle as $CommentofThisArticle):?>  
      <div class="">
            <div class="">
              <div class="">
                <p class=""><?=$CommentofThisArticle['content'];?></p>
                <p class=""><small class="-">Écrit par : <?=$CommentofThisArticle['pseudo'];?></small></p>
                <p class=""><small class="-">Publié le : <?=(new DateTimeImmutable($CommentofThisArticle['date_publication']))->format('d/m/Y') ;?></small></p>
              </div>
            </div>
          </div>

    <?php endforeach;?>
  <?php endif;?>
  </div>
