<div class="Category">
  <?php if (isset($articlesbyCategory[0]['category'])) :?>
      <h3 class="Category-title">Catégorie : <?=$articlesbyCategory[0]['category'];?></h3>
      <?php foreach ($articlesbyCategory as $articlebyCategory):?>
            <div class="Category-box">
              <div class="category-box-infos">
                  <h5 class="Category-box-infos-h5"><?=$articlebyCategory['title'];?></h5>
                  <p class="Category-box-infos-resume"><?= mb_substr($articlebyCategory['content'], 0, 150);?> [...]</p>
                  <p class="Category-box-infos-pseudo">Écrit par : <?=$articlebyCategory['pseudo'];?></p>
                  <p class=""><small class="Category-box-infos-category">Catégorie : <a href="<?=buildUrl('categorie', ['id' => intval($articlebyCategory['category_id'])]);?>"><?= $articlebyCategory['category'] ;?></small></p></a>
                  <p class=""><small class="Category-box-infos-date">Publié le : <?= (new DateTimeImmutable($articlebyCategory['creation_date']))->format('d/m/Y') ;?></small></p>
                  <a href="<?=buildUrl('article', ['id' => intval($articlebyCategory['id_article'])]);?>" class="btn btn-primary">Lire l'article</a>
                  </div>
            </div>
      <?php endforeach;?>
    <?php endif;?>
</div>
