<footer class="Footer">
    <section class="Footer-colonne1">
        <h3 class="Footer-colonne1-h3">Histoire & Philosophie</h3>
        <img class="Footer-colonne1-img" src="<?=asset('/img/history.png');?>" alt="">
    </section>
    <section class="Footer-colonne2">
        <h3 class="Footer-colonne2-h3">Contactez-nous</h3>
        <p class="Footer-email">Email : nico13sanna@gmail.com</p>
    </section>
    <section class="Footer-colonne3">
        <h3 class="Footer-colonne3-h3">Liens rapides</h3>
        <a class="Footer-colonne3-a" href="/">Accueil</a>
        <a class="Footer-colonne3-a" href="">Politique de confidentialité</a>
    </section>
    <section class="Footer-colonne4"> 
        <h4 class="Footer-colonne4-h4 ">Copyright Nicolas Sanna 2021</h4>
    </section>
</footer>