<h3 class="title text-center">Inscription</h3>

<?php if(isset($_SESSION['auth'])) :?>

   <p> Vous êtes déjà connecté. </p>
   
<?php else:?>

<form method="POST">
    <div class="">
        <label for="exampleInputEmail1" class="">Nom :</label>
        <input type="text"  class="form-control" name="lastname">
    </div>
    <div class="">
        <label for="exampleInputEmail1" class="">Prénom :</label>
        <input type="text"  class="form-control" name="firstname">
    </div>
    <div class="">
        <label for="exampleInputEmail1" class="">Pseudo (il sera visible sur tout le site) :</label>
        <input type="text"  class="form-control"  name="pseudo">
    </div>
    <div class="">
        <label for="exampleInputEmail1" class="">E-mail : </label>
        <input type="email" class="form-control" name="email">
    </div>
    <div class="">
        <label for="exampleInputPassword1" class="">Mot de passe :</label>
        <input type="password"  required class="form-control" class="password" name="password">
    </div>
    <button type="submit" class="btn btn-primary" name="validate">S'inscrire</button>
    <br><br>
    <a href="<?=buildUrl('connexion');?>"><p>J'ai déjà un compte, je me connecte</p></a>
    </form>

<?php endif;?>
