<header class="Header">
  <nav class="Header-nav">
    <img class="Header-img" src="<?=asset('img/history.png');?>" alt="">
    <a class="Header-nav-a" href="<?=buildUrl('homepage');?>">Histoire & Philosophie</a>
    <div class="Header-burger-cont" id="Burger">
      <div class="Header-burger-ico" href="#"></div>
    </div>
    <div class="Header-nav-menu" id="Menu">
      <div class="Header-burger-fermer" id="BurgerOff">
        <img src="<?=asset('img/delete.png');?>" class="Header-burger-fermer-img">
      </div>
        <ul class="Header-nav-ul">
          <li class="Header-nav-ul-li">
              <a class="Header-nav-ul-li-a" href="<?=buildUrl('forum');?>">Tous les articles</a>
            </li>
            <li class="Header-nav-ul-li">
              <a class="Header-nav-ul-li-a" href="<?=buildUrl('categories');?>">Catégories</a>
            </li>

            <li class="Header-nav-ul-li">
              <a class="Header-nav-ul-li-a" href="<?=buildUrl('forum');?>">Forum</a>
            </li>

            <?php if(isset($_SESSION['auth'])):?>

            <li class="Header-nav-ul-li">
              <a class="Header-nav-ul-li-a">Bonjour <?=$_SESSION['pseudo'];?></a>
            </li>

            <li class="Header-nav-ul-li">

              <a class="Header-nav-ul-li-a" id="Admin">
                Administration
              </a>

              <ul class="Header-nav-ul-admin" id="adminSousMenu">

                <li><a class="Header-nav-ul-admin-li-a" href="<?=buildUrl('creerunarticle');?>">Publier un article</a>

                <li><a class="Header-nav-ul-admin-li-a" href="<?=buildUrl('mesarticles');?>">Mes articles</a>

                <?php if(isset($_SESSION['administrator'])):?>

                <li><a class="Header-nav-ul-admin-li-a" href="<?=buildUrl('creercategorie');?>">Créer une catégorie</a>

                <?php endif;?>

              </ul>

            </li>

            <li class="Header-nav-ul-li">
                <a class="Header-nav-ul-li-a" href="<?=buildUrl('deconnexion');?>">Déconnexion</a>
            </li>

            <?php else:?>

            <li class="Header-nav-ul-li">
              <a class="Header-nav-ul-li-a" href="<?=buildUrl('inscription');?>">Inscription</a>
            </li>
            <li class="Header-nav-ul-li">
              <a class="Header-nav-ul-li-a" href="<?=buildUrl('connexion');?>">Connexion</a>
            </li>

            <?php endif;?>

          </li>
        </ul>
    </div>
  </nav>
</header>
