<h3 class="">Mes articles publiés</h3>
  <br>
<div class="">
<?php if (isset($myArticles)):?>  
  <?php foreach ($myArticles as $myArticle):?>
      <div class="">
        <div class="">
          <div class="">
            <h5 class=""><?=$myArticle['title'];?></h5>
            <br>
            <p class=""><?=mb_substr($myArticle['content'], 0, 150);?> [...]</p>
            <p class="">Catégorie : <a href="/categorie?id=<?=$myArticle['category_id'];?>"><?= $myArticle['category'] ;?></p></a>
            <p class="">>Publié le : <?= (new DateTimeImmutable($myArticle['creation_date']))->format('d/m/Y') ;?></p>
            <a href="<?=buildUrl('article', ['id' => intval($myArticle['article_id'])]);?>" class="btn btn-primary">Lire l'article</a>
            <a href="<?=buildUrl('editerarticle', ['id' => intval($myArticle['article_id']), 'jeton' => $_SESSION['jeton']]);?>" class="">Modifier l'article</a>
            <a href="<?=buildUrl('supprimerarticle', ['id' => intval($myArticle['article_id']), 'jeton' => $_SESSION['jeton']]);?>" id="article-<?=$myArticle['article_id'];?>" class="supprimer">Supprimer l'article</a>     
          </div>
        </div>
      </div>
    <br>
  <?php endforeach;?>
</div>
<?php endif;?>

